apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart

# replicaset
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: cart

  # pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: cart
    spec:
      containers:
      - name: cart
        image: venkey57/cart:4.0.0
        envFrom:
        - configMapRef:
            name: cart 
---

apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  # servicer labels
  labels:
    project: roboshop
    tier: backend
    component: cart
spec:
  type: ClusterIP        # Defines the type of service
  selector:
    project: roboshop   # Finds Pods labeled with "project, tier, compnent"
    tier: backend
    component: cart     
  ports:
    - protocol: TCP
      port: 8080          # The port exposed by the service
      targetPort: 8080   # The port the container is listening on
