apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # labels related to deployment resource
  labels:
    project: roboshop
    tier: backend
    component: shipping

spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
      
  # Pod
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
      - name: shipping
        image: joindevops/shipping:4.0.0
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  # servicer labels
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec:
  # Service uses the below labels to select the pods
  selector:
    project: roboshop
    tier: backend
    component: shipping
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port